# Compiles shaders/PatchDescriptors.slang to SPIR-V and embeds the bytes into
# src/PatchDescriptorsSpv.h, which is checked in. Embedding the shader means
# consumers of the library need neither a shader compiler at build time nor a
# .spv file next to their executable at runtime.
#
# Run after editing the shader (slangc must be on PATH, or pass -DSLANGC=...):
#
#     cmake -P ngapi/cmake/EmbedPatchDescriptors.cmake
#
# or build the ngapi-embed-patch-descriptors target in the full repo. Use the
# pinned slangc from ci/Dockerfile to keep the checked-in header reproducible:
#
#     docker run --rm -v "$PWD":/src -w /src ngapi-ci \
#         cmake -P ngapi/cmake/EmbedPatchDescriptors.cmake

cmake_minimum_required(VERSION 3.22)

get_filename_component(NGAPI_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SLANG_SOURCE "${NGAPI_DIR}/shaders/PatchDescriptors.slang")
set(HEADER "${NGAPI_DIR}/src/PatchDescriptorsSpv.h")

if(NOT SLANGC)
    find_program(SLANGC slangc)
endif()
if(NOT SLANGC)
    message(FATAL_ERROR "slangc not found; put it on PATH or pass -DSLANGC=/path/to/slangc")
endif()

set(SPV "${HEADER}.spv.tmp")
execute_process(
    COMMAND "${SLANGC}" "${SLANG_SOURCE}"
            -target spirv -stage compute -entry main
            -I "${NGAPI_DIR}/include"
            -o "${SPV}"
    RESULT_VARIABLE SLANGC_RESULT)
if(NOT SLANGC_RESULT EQUAL 0)
    file(REMOVE "${SPV}")
    message(FATAL_ERROR "slangc failed (exit code ${SLANGC_RESULT})")
endif()

file(READ "${SPV}" HEX HEX)
file(REMOVE "${SPV}")
string(LENGTH "${HEX}" HEX_LENGTH)
math(EXPR SPV_SIZE "${HEX_LENGTH} / 2")

# "0x03,0x02,..." wrapped at 16 bytes per line. CMake regex has no bounded
# repetition ({16}), so spell the byte pattern out.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX}")
set(B "0x[0-9a-f][0-9a-f],")
string(REGEX REPLACE "(${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B})" "\\1\n    " BYTES "${BYTES}")
string(REGEX REPLACE "[ \n]+$" "" BYTES "${BYTES}")

file(WRITE "${HEADER}.tmp"
"// SPIR-V for the library's internal descriptor-patching compute shader
// (shaders/PatchDescriptors.slang), embedded so building and running the
// library needs neither a shader compiler nor a .spv file on disk.
//
// Generated by cmake/EmbedPatchDescriptors.cmake -- do not edit by hand.
// Regenerate after editing the shader (see that script for instructions).
// clang-format off
#ifndef NGAPI_PATCH_DESCRIPTORS_SPV_H
#define NGAPI_PATCH_DESCRIPTORS_SPV_H

#include <cstdint>

inline constexpr uint8_t NgapiPatchDescriptorsSpv[${SPV_SIZE}] = {
    ${BYTES}
};

#endif // NGAPI_PATCH_DESCRIPTORS_SPV_H
// clang-format on
")

execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${HEADER}.tmp" "${HEADER}")
file(REMOVE "${HEADER}.tmp")
message(STATUS "Embedded ${SPV_SIZE} bytes of SPIR-V into ${HEADER}")
